apiVersion: test.com/v1alpha1



kind: AppClaim



metadata:



  name: application-deploy-test



  labels:



    app-owner: Saba



spec:



  id: caddy



  compositionSelector:



    matchLabels:



      type: appdeploy



  parameters:



    namespace: automation



    image: caddy



    host: applicationtest.caddy.com


