apiVersion: test.com/v1alpha1



kind: AppClaim



metadata:



  name: application-deploy-test



  labels:



    app-owner: Saba



spec:



  id: apache



  compositionSelector:



    matchLabels:



      type: appdeploy



  parameters:



    namespace: saba



    image: httpd



    host: applicationtest.apache.com


